### ISSUE TITLE
Format details on book list

### ISSUE THREAD

**Issue by StevenAime** [joshzcold/JCold_UVU_MVC#12]
I think it would improve readability of the site if we somehow incorporated a format on the student detail as something of a list..
found some links
https://forums.asp.net/t/2114478.aspx?How+would+one+get+a+list+into+a+viewbag+and+then+get+that+viewbag+to+display+on+a+create+view+form+Also+is+it+possible+to+use+a+webform+control+on+an+mvc+page+
https://www.c-sharpcorner.com/UploadFile/219d4d/viewbag-and-viewdata-in-mvc109/
http://www.tutorialsteacher.com/mvc/viewbag-in-asp.net-mvc

**Comment by joshzcold** [comment]
This might be fixable, but is a small feature fix compared to the amount of research I would have to do to fix it
