### ISSUE TITLE
Troubleshootings by Steven

### ISSUE THREAD

**Issue by StevenAime** [joshzcold/JCold_UVU_MVC#3]
I'm attaching a word document noting my recommendations and some issues I'm reading..
It would also help that when checking out a book and you have an invalid field, instead of creating a new page, somehow throw a flag to prevent the page from progressing to the next and highlighting the invalid field
\
[Aime TroubleShooting website.docx](https://github.com/joshzcold/JCold_UVU_MVC/files/1900688/Aime.TroubleShooting.website.docx)

**Comment by joshzcold** [comment]
Reverse the Due Date and Check Out Date: Fixed

 
Currency display: Fixed

 Mouseover event recommended for those who don’t know what the icons mean
That or a legend, but a mouseover would be more easy to read and note: Fixed

 
ISBN, auto-format..: Can't implement for now marking as closed.
