### ISSUE TITLE
Checkout Book & Supplies edit page

### ISSUE THREAD

**Issue by 10758637** [joshzcold/JCold_UVU_MVC#4]
![checkout](https://user-images.githubusercontent.com/36175843/38646996-60b53fea-3da7-11e8-83c6-e23a1df6c3d2.PNG)
![checkout2](https://user-images.githubusercontent.com/36175843/38647004-66a3e578-3da7-11e8-8bbc-4d72f1c3c777.PNG)
It looks like an error

**Comment by joshzcold** [comment]
I'll make these not look like errors. thanks for the suggestion

**Comment by joshzcold** [comment]
Fixed in latest commit. 
![image](https://user-images.githubusercontent.com/36175703/38698195-78a0804c-3e51-11e8-9575-e8ceaf4aee8b.png)
