### ISSUE TITLE
Books & Supplies Filter

### ISSUE THREAD

**Issue by 10758637** [joshzcold/JCold_UVU_MVC#5]
![image](https://user-images.githubusercontent.com/36175843/38647100-d636b906-3da7-11e8-8716-a3d2d90c09d9.png)
![image 1](https://user-images.githubusercontent.com/36175843/38647104-d8434368-3da7-11e8-8af8-5e8063e098f4.png)
‘Available’ shows all lists are true even if some books and supplies are not available.

**Comment by joshzcold** [comment]
I fixed this in the books and supplies controller using code like this 

      var SetAvailableSuppliesTrue =
            from chkb in db.CheckOutSupplies
            join bk in db.Supplies
            on chkb.SuppliesID equals bk.SuppliesID
            where chkb.SuppliesID == bk.SuppliesID && chkb.ReturnedSupply == true
            select bk;
            foreach (Supplies chkb in SetAvailableSuppliesTrue)
            {
                chkb.Available = true;
            }

            var SetAvailableSuppliesFalse =
            from chkb in db.CheckOutSupplies
            join bk in db.Supplies
            on chkb.SuppliesID equals bk.SuppliesID
            where chkb.SuppliesID == bk.SuppliesID && chkb.ReturnedSupply == false
            select bk;
            foreach (Supplies chkb in SetAvailableSuppliesFalse)
            {
                chkb.Available = false;
            }

Now the website will update the correct values to the database so that the filter functions work as expected. The problem was one query overwriting another, so now they work together
