### ISSUE TITLE
Supply Search

### ISSUE THREAD

**Issue by 10758637** [joshzcold/JCold_UVU_MVC#7]
![image 2](https://user-images.githubusercontent.com/36175843/38647145-1703b36c-3da8-11e8-9254-7fd057269d10.png)
I didn't login admin account, but there is ‘Create Supply’ button after searching some supplies.

**Comment by joshzcold** [comment]
Fixed in latest commit. Good Catch!
![image](https://user-images.githubusercontent.com/36175703/38649627-f886941a-3db4-11e8-84ac-0cd9571a411e.png)
