### ISSUE TITLE
Adding students

### ISSUE THREAD

**Issue by 10758637** [joshzcold/JCold_UVU_MVC#8]
![image 3](https://user-images.githubusercontent.com/36175843/38647190-46a5c808-3da8-11e8-9dce-7c5263f73f02.png)
Admin can add students who have same UVU ID. I think it shouldn't be possible to add students with existing UVU ID, Email, and Phone number.

**Comment by joshzcold** [comment]
I will look into how hard it would be to only allow unique values from the model

**Comment by joshzcold** [comment]
This would be outside the scope of the delivery closing
